iter18
alexlzrv/go-metrics-alerting pull request #18
Opened 2023-08-20 10:25 UTC by alexlzrv

2023-08-25 15:49 UTC, s-shpak requested changes
1. Пожалуйста, добавь в проект линтер и поправь его замечания: https://github.com/s-shpak/praktikum-golangci-lint
2. Общее покрытие тестами должно составлять не менее 40%, сейчас у тебя 32.6% (см. как считать здесь https://stackoverflow.com/questions/33444968/how-to-get-all-packages-code-coverage-together-in-go)
3. Добавь инструкции по запуску godoc в README.md

2023-08-29 18:44 UTC, alexlzrv commented
@s-shpak поправил все важные замечания по линтеру, но он показывает много неправильного и нелогичного.
изменил Readme

2023-08-30 19:15 UTC, s-shpak requested changes
1. Текущее тестовое покрытие: 39.5%, но должно быть >= 40%
2. Я не увидел практически ничего нелогичного в отчете линтера. Если ты не хочешь править эти проблемы, то я не могу от тебя требовать использование линтера. Но если хочешь разобраться, то можем обсудить его вывод на 1-1

2023-09-01 20:55 UTC, s-shpak approved these changes

2023-09-03 09:15 UTC, merged